apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: romantic-jellyfish-nodejs 
  janus-idp.io/tekton: romantic-jellyfish-nodejs
  backstage.io/kubernetes-id: romantic-jellyfish-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: romantic-jellyfish-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  